version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/toilet-review
      - JWT_SECRET=your_secure_jwt_secret_here
    volumes:
      - ./logs:/app/logs
      - ./public:/usr/share/nginx/html
    depends_on:
      - mongodb
    networks:
      - toilet-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - toilet-network

volumes:
  mongodb_data:
    driver: local

networks:
  toilet-network:
    driver: bridge 